#!/bin/sh

BOARD="$(cat /tmp/sysinfo/board_name 2>/dev/null || true)"
[ "$BOARD" = "airpi,ap3000m" ] || exit 0

LOG="/tmp/airpi-oldfw-network-defaults.log"
exec >>"$LOG" 2>&1

echo "[Airpi] applying safe old firmware compatible defaults"
date

# IMPORTANT:
# Do not create named br-lan UCI section.
# Do not delete bridge ports.
# Let chasey board.d/config_generate create br-lan = eth0.
# Only apply old project parameters.

uci set system.@system[0].hostname='Airpi' 2>/dev/null || true

uci -q batch <<'EOC'
set network.lan=interface
set network.lan.device='br-lan'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.88.1'
set network.lan.netmask='255.255.255.0'
set network.lan.ip6assign='60'

set network.wan=interface
set network.wan.device='eth1'
set network.wan.proto='dhcp'

set network.wan6=interface
set network.wan6.device='eth1'
set network.wan6.proto='dhcpv6'

set dhcp.lan=dhcp
set dhcp.lan.interface='lan'
set dhcp.lan.start='100'
set dhcp.lan.limit='150'
set dhcp.lan.leasetime='12h'
set dhcp.lan.dhcpv4='server'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ra='server'
set dhcp.lan.ra_slaac='1'
set dhcp.lan.max_preferred_lifetime='2700'
set dhcp.lan.max_valid_lifetime='5400'
delete dhcp.lan.ignore
EOC

# QModem old project compatible network.
uci -q batch <<'EOC'
set network.2_1=interface
set network.2_1.modem_config='2_1'
set network.2_1.proto='dhcp'
set network.2_1.metric='11'
set network.2_1.ifname='wwan0_1'
set network.2_1.device='wwan0_1'

set network.2_1v6=interface
set network.2_1v6.modem_config='2_1'
set network.2_1v6.proto='dhcpv6'
set network.2_1v6.metric='11'
set network.2_1v6.extendprefix='1'
EOC

# Firewall old project compatible layout.
if ! uci -q show firewall.@zone[0] >/dev/null 2>&1; then
  uci -q add firewall zone >/dev/null
fi

if ! uci -q show firewall.@zone[1] >/dev/null 2>&1; then
  uci -q add firewall zone >/dev/null
fi

uci -q batch <<'EOC'
set firewall.@zone[0].name='lan'
set firewall.@zone[0].network='lan'
set firewall.@zone[0].input='ACCEPT'
set firewall.@zone[0].output='ACCEPT'
set firewall.@zone[0].forward='ACCEPT'

set firewall.@zone[1].name='wan'
delete firewall.@zone[1].network
add_list firewall.@zone[1].network='wan'
add_list firewall.@zone[1].network='wan6'
add_list firewall.@zone[1].network='2_1'
add_list firewall.@zone[1].network='2_1v6'
set firewall.@zone[1].input='REJECT'
set firewall.@zone[1].output='ACCEPT'
set firewall.@zone[1].forward='REJECT'
set firewall.@zone[1].masq='1'
set firewall.@zone[1].mtu_fix='1'
EOC

if ! uci -q show firewall | grep -q "src='lan'.*dest='wan'"; then
  uci -q add firewall forwarding >/dev/null
  uci -q set firewall.@forwarding[-1].src='lan'
  uci -q set firewall.@forwarding[-1].dest='wan'
fi

# QModem profile.
uci -q batch <<'EOC'
set qmodem.main=main
set qmodem.main.enable_dial='1'
set qmodem.main.try_preset_usb='1'
set qmodem.main.try_preset_pcie='1'
set qmodem.main.enable_pcie_scan='1'
set qmodem.main.start_delay='0'
set qmodem.main.modem_count='1'

set qmodem.2_1=modem-device
set qmodem.2_1.path='/sys/bus/usb/devices/2-1/'
set qmodem.2_1.data_interface='usb'
set qmodem.2_1.enable_dial='1'
set qmodem.2_1.soft_reboot='1'
set qmodem.2_1.extend_prefix='1'
set qmodem.2_1.pdp_type='ipv4v6'
set qmodem.2_1.state='enabled'
set qmodem.2_1.metric='11'
set qmodem.2_1.name='rg520f-eb'
set qmodem.2_1.network='wwan0'
set qmodem.2_1.manufacturer='quectel'
set qmodem.2_1.platform='qualcomm'
set qmodem.2_1.wcdma_band='1/5/8'
set qmodem.2_1.lte_band='1/3/5/7/8/20/28/32/38/40/41/42/43/71'
set qmodem.2_1.nsa_band='1/3/5/7/8/20/28/38/40/41/71/75/76/77/78'
set qmodem.2_1.sa_band='1/3/5/7/8/20/28/38/40/41/71/75/76/77/78'
set qmodem.2_1.at_port='/dev/ttyUSB2'
set qmodem.2_1.valid_at_ports='/dev/ttyUSB2'

delete qmodem.2_1.modes
add_list qmodem.2_1.modes='qmi'
add_list qmodem.2_1.modes='gobinet'
add_list qmodem.2_1.modes='ecm'
add_list qmodem.2_1.modes='mbim'
add_list qmodem.2_1.modes='rndis'
add_list qmodem.2_1.modes='ncm'

delete qmodem.2_1.ports
add_list qmodem.2_1.ports='/dev/ttyUSB0'
add_list qmodem.2_1.ports='/dev/ttyUSB1'
add_list qmodem.2_1.ports='/dev/ttyUSB2'
add_list qmodem.2_1.ports='/dev/ttyUSB3'
EOC

for svc in dnsmasq firewall network eqos qmodem qmodem_init turboacc qmodem_reboot qmodem_network ttyd; do
  if [ -x "/etc/init.d/$svc" ]; then
    /etc/init.d/"$svc" enable >/dev/null 2>&1 || true
  fi
done

uci commit system
uci commit network
uci commit dhcp
uci commit firewall
uci commit qmodem 2>/dev/null || true

echo "[Airpi] final network:"
uci show network | grep -E 'br-lan|eth0|eth1|lan|wan|2_1' || true

rm -f /etc/uci-defaults/99-airpi-oldfw-network
exit 0
